//! Behavior-NN inference: keypoint track → behavior class, in Rust via ONNX.
//!
//! The model is produced offline by `training/train.py` (PyTorch → ONNX, the
//! one declared-Python piece of the stack); this module runs it. Input
//! contract `[1, T, 17, 6]` with channels `(x, y, conf, velocity, gdx, gdy)`:
//!
//!   * x, y — BOX-RELATIVE: translated to the person box's top-left and
//!     divided by box height, so distance from camera cancels out;
//!   * conf — per-joint confidence passed through (the net learns to
//!     discount noisy night/IR joints);
//!   * velocity — per-joint frame-to-frame delta magnitude, 0 at gaps/t0;
//!   * gdx, gdy — GLOBAL motion: box-center travel per frame in box-height
//!     units, replicated across joints. Box-relative x/y erase
//!     walk-across-frame travel (translation invariance); these put it
//!     back, scale-normalized. 0 at gaps/t0.
//!
//! `normalize_track` MUST stay numerically identical to
//! `training/dataset.py::track_to_tensor` — train-time and inference-time
//! featurization drifting apart is the classic silent killer of deployed
//! models. The guarantee is mechanical, not aspirational:
//! `testdata/feature_parity.json` is GENERATED by the Python side
//! (`training/gen_parity_fixture.py`) and replayed here as a unit test.
//! If either side changes, the test breaks before production does.
//!
//! Model sidecar: `train.py` writes `<model>.classes.json` next to the ONNX —
//! `{"classes": […], "seq_len": 16, "min_joint_conf": 0.0}` — so inference
//! can never run with a different sequence length or masking threshold than
//! the weights were trained with.

use anyhow::{ensure, Context, Result};
use ort::session::Session;

use crate::pose::NUM_KP;

pub const CHANNELS: usize = 6;

/// One frame of one person track, as exported in the corpus JSONL.
#[derive(Clone, Debug)]
pub struct TrackFrame {
    /// x1, y1, x2, y2 (source pixels).
    pub bbox: [f32; 4],
    /// 17 × (x, y, conf), source pixels.
    pub kps: [[f32; 3]; NUM_KP],
}

/// Training-config sidecar loaded from `<model>.classes.json`.
#[derive(Clone, Debug)]
pub struct ModelMeta {
    pub classes: Vec<String>,
    pub seq_len: usize,
    pub min_joint_conf: f32,
    /// Feature channels the model was trained with — must equal CHANNELS.
    pub channels: usize,
}

impl Default for ModelMeta {
    fn default() -> Self {
        Self { classes: Vec::new(), seq_len: 16, min_joint_conf: 0.0, channels: CHANNELS }
    }
}

/// Mirror of `dataset.py::track_to_tensor`. Returns the flat `[T*17*4]`
/// feature vector + visibility (fraction of frames the person was present).
///
/// Subsample/pad indices are computed in f64 (Python floats are f64; the
/// rounding can never land on an exact .5, so round() agrees across both
/// languages — see the parity fixture for the proof in numbers).
pub fn normalize_track(
    frames: &[Option<TrackFrame>],
    seq_len: usize,
    min_joint_conf: f32,
) -> (Vec<f32>, f32) {
    // Uniform subsample / right-pad to seq_len.
    let mut sel: Vec<Option<TrackFrame>> = if frames.len() > seq_len {
        (0..seq_len)
            .map(|i| {
                let idx = ((i as f64) * ((frames.len() - 1) as f64)
                    / ((seq_len - 1) as f64))
                    .round() as usize;
                frames[idx].clone()
            })
            .collect()
    } else {
        frames.to_vec()
    };
    while sel.len() < seq_len {
        sel.push(None);
    }

    let mut out: Vec<f32> = Vec::with_capacity(seq_len * NUM_KP * CHANNELS);
    let mut prev: [Option<(f32, f32)>; NUM_KP] = [None; NUM_KP];
    let mut prev_center: Option<(f32, f32)> = None;
    let mut present = 0usize;
    for f in &sel {
        match f {
            None => {
                out.extend(std::iter::repeat(0.0).take(NUM_KP * CHANNELS));
                prev = [None; NUM_KP];
                prev_center = None;
            }
            Some(tf) => {
                present += 1;
                let h = (tf.bbox[3] - tf.bbox[1]).max(1.0);
                let cx = (tf.bbox[0] + tf.bbox[2]) / 2.0;
                let cy = (tf.bbox[1] + tf.bbox[3]) / 2.0;
                // Global motion: box-center travel in box-heights
                // (per-person info, replicated across joints).
                let (gdx, gdy) = match prev_center {
                    None => (0.0, 0.0),
                    Some((pcx, pcy)) => ((cx - pcx) / h, (cy - pcy) / h),
                };
                prev_center = Some((cx, cy));
                for j in 0..NUM_KP {
                    let [kx, ky, c] = tf.kps[j];
                    let x = (kx - tf.bbox[0]) / h;
                    let y = (ky - tf.bbox[1]) / h;
                    if c < min_joint_conf {
                        // Joint invisible — zero its local channels but KEEP
                        // global motion: travel is known even when a limb isn't.
                        out.extend([0.0, 0.0, 0.0, 0.0, gdx, gdy]);
                        prev[j] = None;
                        continue;
                    }
                    let v = match prev[j] {
                        None => 0.0,
                        Some((px, py)) => ((x - px).powi(2) + (y - py).powi(2)).sqrt(),
                    };
                    out.extend([x, y, c, v, gdx, gdy]);
                    prev[j] = Some((x, y));
                }
            }
        }
    }
    (out, present as f32 / seq_len.max(1) as f32)
}

fn softmax(logits: &[f32]) -> Vec<f32> {
    let m = logits.iter().cloned().fold(f32::NEG_INFINITY, f32::max);
    let exps: Vec<f32> = logits.iter().map(|&v| (v - m).exp()).collect();
    let s: f32 = exps.iter().sum();
    exps.iter().map(|&e| e / s.max(1e-12)).collect()
}

/// Run the behavior model on one normalized track → class probabilities.
pub fn classify(session: &Session, flat: &[f32], seq_len: usize) -> Result<Vec<f32>> {
    ensure!(
        flat.len() == seq_len * NUM_KP * CHANNELS,
        "feature length {} != T*17*4 for T={seq_len}", flat.len(),
    );
    let arr = ndarray::Array::from_shape_vec(
        (1usize, seq_len, NUM_KP, CHANNELS),
        flat.to_vec(),
    )?;
    let outputs = session.run(ort::inputs!["x" => arr.view()]?)?;
    let logits = outputs["logits"].try_extract_tensor::<f32>()?;
    let row: Vec<f32> = logits.iter().cloned().collect();
    Ok(softmax(&row))
}

/// Load the training-config sidecar written by train.py. Tolerates the
/// legacy bare-array form (classes only, defaults for the rest).
pub fn load_meta(model_path: &str) -> ModelMeta {
    let path = format!("{model_path}.classes.json");
    let Ok(text) = std::fs::read_to_string(&path) else {
        return ModelMeta::default();
    };
    let Ok(v) = serde_json::from_str::<serde_json::Value>(&text) else {
        return ModelMeta::default();
    };
    let mut meta = ModelMeta::default();
    match &v {
        serde_json::Value::Array(items) => {
            meta.classes = items.iter()
                .filter_map(|s| s.as_str().map(String::from)).collect();
        }
        serde_json::Value::Object(map) => {
            if let Some(serde_json::Value::Array(items)) = map.get("classes") {
                meta.classes = items.iter()
                    .filter_map(|s| s.as_str().map(String::from)).collect();
            }
            if let Some(n) = map.get("seq_len").and_then(|x| x.as_u64()) {
                meta.seq_len = n as usize;
            }
            if let Some(c) = map.get("min_joint_conf").and_then(|x| x.as_f64()) {
                meta.min_joint_conf = c as f32;
            }
            if let Some(n) = map.get("channels").and_then(|x| x.as_u64()) {
                meta.channels = n as usize;
            }
        }
        _ => {}
    }
    meta
}

/// Parse a corpus line's `frames` array (see export_pose_dataset.py) into
/// track frames. Frames with malformed/short keypoints become gaps rather
/// than wrong numbers. Returns None when the line has no `frames` (e.g. a
/// `--raw` export line).
pub fn parse_frames(rec: &serde_json::Value) -> Option<Vec<Option<TrackFrame>>> {
    let frames = rec.get("frames")?.as_array()?;
    let mut out: Vec<Option<TrackFrame>> = Vec::with_capacity(frames.len());
    for f in frames {
        if f.is_null() {
            out.push(None);
            continue;
        }
        let parsed = (|| -> Option<TrackFrame> {
            let b = f.get("box")?;
            let bbox = [
                b.get("x1")?.as_f64()? as f32,
                b.get("y1")?.as_f64()? as f32,
                b.get("x2")?.as_f64()? as f32,
                b.get("y2")?.as_f64()? as f32,
            ];
            let karr = f.get("kps").or_else(|| f.get("keypoints"))?.as_array()?;
            if karr.len() != NUM_KP {
                return None;
            }
            let mut kps = [[0.0f32; 3]; NUM_KP];
            for (j, kp) in karr.iter().enumerate() {
                let t = kp.as_array()?;
                kps[j] = [
                    t.first()?.as_f64()? as f32,
                    t.get(1)?.as_f64()? as f32,
                    t.get(2)?.as_f64()? as f32,
                ];
            }
            Some(TrackFrame { bbox, kps })
        })();
        out.push(parsed);
    }
    Some(out)
}

/// CLI: `spike behavior <model.onnx> <corpus.jsonl> [max-lines]` — classify
/// exported tracks with the trained NN and print the verdicts.
pub fn run_behavior_spike(model: &str, corpus: &str, max_lines: usize) -> Result<()> {
    let session = crate::build_session(model)?;
    let meta = load_meta(model);
    ensure!(
        meta.channels == CHANNELS,
        "model was trained with {} feature channels but this binary produces {} \
         — retrain (training/train.py) or use a matching binary",
        meta.channels, CHANNELS,
    );
    let class_name = |i: usize| -> String {
        meta.classes.get(i).cloned().unwrap_or_else(|| format!("class_{i}"))
    };
    println!(
        "behavior spike · model {model} · T={} min_joint_conf={} · classes: {}",
        meta.seq_len, meta.min_joint_conf,
        if meta.classes.is_empty() { "(none — showing indices)".into() }
        else { meta.classes.join(", ") },
    );

    let text = std::fs::read_to_string(corpus)
        .with_context(|| format!("read {corpus}"))?;
    let mut n = 0usize;
    for line in text.lines() {
        if n >= max_lines {
            break;
        }
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let rec: serde_json::Value = match serde_json::from_str(line) {
            Ok(v) => v,
            Err(_) => continue,
        };
        let Some(frames) = parse_frames(&rec) else { continue };
        let sample = rec.get("sample_id").or_else(|| rec.get("event_id"))
            .and_then(|v| v.as_str()).unwrap_or("<no-id>").to_string();
        let (flat, vis) = normalize_track(&frames, meta.seq_len, meta.min_joint_conf);
        let probs = classify(&session, &flat, meta.seq_len)?;
        let (top, p) = probs.iter().enumerate()
            .max_by(|a, b| a.1.partial_cmp(b.1).unwrap())
            .map(|(i, p)| (i, *p)).unwrap_or((0, 0.0));
        println!(
            "  {sample} → {} (p={p:.2}, visibility {:.0}%)",
            class_name(top), vis * 100.0,
        );
        n += 1;
    }
    println!("\n  ▶ classified {n} track(s)");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// THE train/infer parity gate: replay the fixture the Python side
    /// generated from dataset.py::track_to_tensor and demand numeric
    /// agreement. Regenerate with `python training/gen_parity_fixture.py`
    /// whenever either featurizer changes — a missing fixture is a failure,
    /// not a skip, because silently skipping is how drift ships.
    #[test]
    fn featurization_matches_python_dataset_py() {
        let path = concat!(env!("CARGO_MANIFEST_DIR"), "/testdata/feature_parity.json");
        let text = std::fs::read_to_string(path).expect(
            "testdata/feature_parity.json missing — run `python training/gen_parity_fixture.py`",
        );
        let v: serde_json::Value = serde_json::from_str(&text).unwrap();
        let seq_len = v["seq_len"].as_u64().unwrap() as usize;
        let min_conf = v["min_joint_conf"].as_f64().unwrap() as f32;
        let frames = parse_frames(&v).expect("fixture has frames");
        let expected: Vec<f32> = v["expected"].as_array().unwrap()
            .iter().map(|x| x.as_f64().unwrap() as f32).collect();
        let exp_vis = v["visibility"].as_f64().unwrap() as f32;

        let (got, vis) = normalize_track(&frames, seq_len, min_conf);
        assert_eq!(got.len(), expected.len(), "feature vector length");
        for (i, (a, b)) in got.iter().zip(expected.iter()).enumerate() {
            assert!(
                (a - b).abs() < 1e-4,
                "feature[{i}] diverged: rust={a} python={b}",
            );
        }
        assert!((vis - exp_vis).abs() < 1e-6, "visibility: rust={vis} python={exp_vis}");
    }

    #[test]
    fn gap_resets_velocity() {
        // NOTE: features are BOX-relative, so moving box+person together is
        // zero velocity by design (translation invariance). Velocity must
        // come from the limb moving WITHIN the box — so move the keypoint,
        // keep the box fixed.
        let mk = |kx: f32| TrackFrame {
            bbox: [0.0, 0.0, 50.0, 100.0],
            kps: [[kx, 20.0, 0.9]; NUM_KP],
        };
        // present, present (limb moved → velocity), gap, present (reset)
        let frames = vec![Some(mk(10.0)), Some(mk(20.0)), None, Some(mk(30.0))];
        let (flat, vis) = normalize_track(&frames, 4, 0.0);
        let v = |t: usize, j: usize| flat[(t * NUM_KP + j) * CHANNELS + 3];
        assert_eq!(v(0, 0), 0.0, "t0 velocity is 0");
        assert!(v(1, 0) > 0.0, "t1 velocity present");
        assert_eq!(v(2, 0), 0.0, "gap row zeroed");
        assert_eq!(v(3, 0), 0.0, "velocity resets after gap");
        assert!((vis - 0.75).abs() < 1e-6);
    }

    #[test]
    fn translation_shows_in_global_channels_not_local() {
        // Box + person move together: box-relative x/y (and per-joint
        // velocity) stay constant — but the global channels must carry the
        // travel. This is the walking-vs-standing fix made testable.
        let mk = |x: f32| TrackFrame {
            bbox: [x, 0.0, x + 50.0, 100.0],
            kps: [[x + 10.0, 20.0, 0.9]; NUM_KP],
        };
        let frames = vec![Some(mk(0.0)), Some(mk(12.0)), Some(mk(24.0))];
        let (flat, _) = normalize_track(&frames, 3, 0.0);
        let ch = |t: usize, j: usize, c: usize| flat[(t * NUM_KP + j) * CHANNELS + c];
        assert_eq!(ch(1, 0, 3), 0.0, "box-relative velocity is 0 (translation-invariant)");
        assert_eq!(ch(0, 0, 4), 0.0, "gdx is 0 at t0");
        assert!((ch(1, 0, 4) - 0.12).abs() < 1e-5, "gdx = 12px / 100px box height");
        assert_eq!(ch(1, 0, 5), 0.0, "no vertical travel");
        assert!((ch(2, 0, 4) - 0.12).abs() < 1e-5, "sustained travel at t2");
    }

    #[test]
    fn short_track_pads_and_long_track_subsamples() {
        let mk = || TrackFrame { bbox: [0.0, 0.0, 50.0, 100.0], kps: [[10.0, 20.0, 0.9]; NUM_KP] };
        let (flat, _) = normalize_track(&vec![Some(mk()); 3], 8, 0.0);
        assert_eq!(flat.len(), 8 * NUM_KP * CHANNELS);
        let (flat, vis) = normalize_track(&vec![Some(mk()); 40], 8, 0.0);
        assert_eq!(flat.len(), 8 * NUM_KP * CHANNELS);
        assert!((vis - 1.0).abs() < 1e-6);
    }
}
